meta_product_name: "MatchMe"
meta_title: "MatchMe - Get matched by people who truly care!"
meta_description: "Whether you’re passionate about finding the right couple, or are looking to get matched and let magic happen. Join us today and let us do all the work! You never know who you might meet!"
meta_image: "Image_meta.png" # should exist in `app/assets/images/`
